english_strings = {
    "level1_tab": "Ciphers",
    "level2_tab": "Encoders/Decoders",
    "level3_tab": "Hashers",
    "level4_tab": "Advanced Encryption",
    "level5_tab": "Smart Decrypt",
    "level6_tab": "Algorithm Mixer",
    "file_encryption_tab": "File Encryption",
    "settings_tab": "Settings",
    "enter_text_cipher": "Enter text to Cipher:",
    "enter_text_encode_decode": "Enter text to Encode/Decode:",
    "enter_text_hash": "Enter text to Hash:",
    "enter_text_encryption": "Enter text to Encrypt/Decrypt:",
    "enter_text_smart_decrypt": "Enter text to Decrypt:",
    "enter_text_mixer": "Enter text to Mix:",
    "clear_button": "Clear",
    "copy_input_button": "Copy Input",
    "paste_button": "Paste",
    "copy_output_button": "Copy Output",
    "select_algorithm_level1": "Select Cipher:",
    "select_algorithm_level2": "Select Algorithm:",
    "select_algorithm_level3": "Select Algorithm:",
    "select_algorithm_level4": "Select Algorithm:",
    "select_algorithm_level6": "Select Algorithms to Mix:",
    "select_algorithm_file": "Select Algorithm:",
    "caesar_shift_label": "Caesar Shift (0-100):",
    "vigenere_key_label": "Vigenere Key:",
    "affine_a_label": "Affine Key 'a':",
    "affine_b_label": "Affine Key 'b':",
    "rail_fence_rails_label": "Number of Rails (1-10):",
    "substitution_key_label": "Substitution Key:",
    "playfair_key_label": "Playfair Key:",
    "symmetric_key_label": "Symmetric Key (hex):",
    "rsa_public_key_label": "Public Key (PEM):",
    "rsa_private_key_label": "Private Key (PEM):",
    "encrypt_button_level1": "Encrypt",
    "decrypt_button_level1": "Decrypt",
    "encode_button_level2": "Encode",
    "decode_button_level2": "Decode",
    "hash_button_level3": "Hash",
    "encrypt_button_level4": "Encrypt",
    "decrypt_button_level4": "Decrypt",
    "decrypt_button_level5": "Smart Decrypt",
    "mix_button_level6": "Mix Algorithms",
    "encrypt_button_file": "Encrypt File",
    "decrypt_button_file": "Decrypt File",
    "select_file_button": "Select File",
    "result_label": "Result:",
    "theme_settings_label": "Theme Settings",
    "language_settings_label": "Language Settings",
    "select_language_label": "Select Language:",
    "color_settings_label": "Color Settings",
    "button_color_label": "Button Color:",
    "use_system_colors_label": "Use System Colors",
    "key_generator_settings_label": "Key Generator Settings",
    "key_size_label": "Key Size (bits):",
    "generate_key_button": "Generate Key",
    "key_result_label": "Generated Key:",
    "rsa_key_generator_label": "RSA Key Pair Generator",
    "rsa_key_size_label": "Key Size (bits):",
    "generate_rsa_key_button": "Generate RSA Key Pair",
    "copy_rsa_public_key_button": "Copy Public Key",
    "copy_rsa_private_key_button": "Copy Private Key",
    "about_crypto_coder": "About Crypto Coder",
    "about_text": """Crypto Coder is a cutting-edge application showcasing cryptographic algorithms for educational purposes.

It includes advanced ciphers, encoding/decoding methods, secure hashing, encryption algorithms, smart decryption, and algorithm mixing.

**Disclaimer:** This tool is for educational use only. For production-level security, rely on vetted cryptographic libraries and best practices.""",
    "clipboard_output_copied": "Output copied to clipboard!",
    "clipboard_input_copied": "Input copied to clipboard!",
    "clipboard_empty": "Clipboard is empty.",
    "algorithm_error_title": "Algorithm Error",
    "vigenere_key_empty_error": "Vigenere Key cannot be empty",
    "affine_key_error": "Affine key 'a' must be coprime to 1114111 and valid",
    "rail_fence_rails_error": "Number of rails must be at least 1",
    "substitution_key_empty_error": "Substitution key cannot be empty",
    "playfair_key_empty_error": "Playfair key cannot be empty",
    "playfair_key_invalid_error": "Playfair key must contain alphabetic characters",
    "polybius_input_error": "Invalid Polybius input: must have even number of digits",
    "invalid_base64_input": "Invalid Base64 input",
    "invalid_url_input": "Invalid URL encoded input",
    "invalid_hex_input": "Invalid Hexadecimal input",
    "invalid_ascii_input": "Invalid ASCII input",
    "invalid_binary_input": "Invalid Binary input",
    "invalid_morse_input": "Invalid Morse code input",
    "invalid_quoted_printable_input": "Invalid Quoted-Printable input",
    "invalid_unicode_escape_input": "Invalid Unicode Escape input",
    "invalid_base32_input": "Invalid Base32 input",
    "invalid_uuencode_input": "Invalid UUEncode input",
    "invalid_md5_input": "Invalid MD5 input",
    "invalid_sha1_input": "Invalid SHA1 input",
    "invalid_sha256_input": "Invalid SHA256 input",
    "invalid_sha512_input": "Invalid SHA512 input",
    "invalid_sha3_256_input": "Invalid SHA3_256 input",
    "invalid_sha3_512_input": "Invalid SHA3_512 input",
    "invalid_blake2b_input": "Invalid BLAKE2b input",
    "invalid_blake2s_input": "Invalid BLAKE2s input",
    "invalid_sha224_input": "Invalid SHA224 input",
    "invalid_sha384_input": "Invalid SHA384 input",
    "invalid_ripemd160_input": "Invalid RIPEMD160 input",
    "invalid_whirlpool_input": "Invalid Whirlpool input",
    "invalid_chacha20_input": "Invalid ChaCha20 input",
    "invalid_tripledes_input": "Invalid Triple DES input",
    "invalid_twofish_input": "Invalid Twofish input",
    "invalid_camellia_input": "Invalid Camellia input",
    "key_generation_error_title": "Key Generation Error",
    "key_copied_clipboard": "Key copied to clipboard!",
    "copy_key_button": "Copy Key",
    "select_color_button": "Select Color",
    "file_selected": "Selected File:",
    "no_file_selected": "No file selected",
    "file_encryption_success": "File encrypted successfully!",
    "file_decryption_success": "File decrypted successfully!",
    "file_encryption_error": "File encryption error",
    "file_decryption_error": "File decryption error",
    "select_file_first": "Please select a file first.",
    "select_folder_button": "Select Folder",
    "hash_detected_title": "Hash Detected",
    "hash_detected_message": "The input appears to be a {0} hash, which is a one-way function and cannot be decrypted. Would you like to attempt to crack it using hardware resources (this may take significant time and resources)?",
    "hash_cracked_message": "Hash {0} cracked: {1}",
    "hash_cracking_failed": "Failed to crack {0} hash. No match found in dictionary.",
    "hash_no_crack_message": "Cannot decrypt {0} hash without cracking. Please provide non-hash input.",
    "encryption_detected_title": "Encryption Detected",
    "encryption_detected_message": "The input may be encrypted with {0}. Would you like to attempt key recovery using hardware resources (this may take significant time)?",
    "key_recovery_rsa_message": "RSA key recovery requires the private key or cryptanalysis, which is not feasible in this version.",
    "key_recovery_symmetric_message": "Attempting to brute-force {0} key (simulated). This requires significant computational resources and is not implemented.",
    "cipher_detected_title": "Cipher Detected",
    "cipher_detected_message": "The input appears to be encrypted with {0}. Would you like to attempt key recovery using hardware resources (this may take significant time)?",
    "cipher_no_crack_message": "Cannot decrypt {0} without key recovery. Please provide a different input.",
    "key_recovery_cipher_message": "Failed to recover {0} key.",
    "key_recovery_failed": "Failed to recover key for {0}.",
    "decode_failed": "Failed to decode: No readable output found",
    "caesar_key_placeholder": "Enter Caesar shift (0-100)",
    "vigenere_key_placeholder": "Enter Vigenere key",
    "affine_key_placeholder": "Enter Affine keys (a,b)",
    "rail_fence_key_placeholder": "Enter number of rails (1-10)",
    "substitution_key_placeholder": "Enter Substitution key",
    "playfair_key_placeholder": "Enter Playfair key",
    "caesar_shift_error": "Caesar shift must be a number between 0 and 100",
    "select_method_label": "Select decryption methods",
    "all_methods": "All Methods",
    "classical_ciphers": "Classical Ciphers",
    "modern_ciphers": "Modern Ciphers",
    "hash_methods": "Hash Cracking",
    "no_methods_selected": "No methods selected for decryption.",
    "invalid_input_format": "Invalid input format for {0}.",
    "processing_timeout": "Processing timeout for {0}. Try a smaller input or fewer methods.",
    "base64_decode_error": "Failed to decode Base64: Invalid format.",
    "cancel_button": "Cancel",
    "decryption_cancelled": "Decryption process cancelled.",
    "testing_algorithms": "Testing algorithms from Ciphers and Encoders/Decoders...",
    "top_readable_results": "Top 5 readable results:",
    "result_number": "Result {0}:",
    "readability_score": "Readability Score: {0}",
    "algorithm_used": "Algorithm: {0}",
    "no_readable_results": "No readable results found. Try a different input."
}

persian_strings = {
    "level1_tab": "رمزگذاری‌ها",
    "level2_tab": "کدگذارها/کدبردارها",
    "level3_tab": "درهم‌سازها",
    "level4_tab": "رمزنگاری پیشرفته",
    "level5_tab": "رمزگشایی هوشمند",
    "level6_tab": "ترکیب‌کننده الگوریتم",
    "file_encryption_tab": "رمزنگاری فایل",
    "settings_tab": "تنظیمات",
    "enter_text_cipher": "متن برای رمزگذاری را وارد کنید:",
    "enter_text_encode_decode": "متن برای کدگذاری/کدبرداری را وارد کنید:",
    "enter_text_hash": "متن برای درهم‌سازی را وارد کنید:",
    "enter_text_encryption": "متن برای رمزگذاری/رمزگشایی را وارد کنید:",
    "enter_text_smart_decrypt": "متن برای رمزگشایی را وارد کنید:",
    "enter_text_mixer": "متن برای ترکیب را وارد کنید:",
    "clear_button": "پاک کردن",
    "copy_input_button": "کپی ورودی",
    "paste_button": "چسباندن",
    "copy_output_button": "کپی خروجی",
    "select_algorithm_level1": "انتخاب رمز:",
    "select_algorithm_level2": "انتخاب الگوریتم:",
    "select_algorithm_level3": "انتخاب الگوریتم:",
    "select_algorithm_level4": "انتخاب الگوریتم:",
    "select_algorithm_level6": "انتخاب الگوریتم‌ها برای ترکیب:",
    "select_algorithm_file": "انتخاب الگوریتم:",
    "caesar_shift_label": "جابجایی سزار (0-100):",
    "vigenere_key_label": "کلید ویژنر:",
    "affine_a_label": "کلید 'a' آفین:",
    "affine_b_label": "کلید 'b' آفین:",
    "rail_fence_rails_label": "تعداد ریل‌ها (1-10):",
    "substitution_key_label": "کلید جایگزینی:",
    "playfair_key_label": "کلید پلی‌فیر:",
    "symmetric_key_label": "کلید متقارن (هگز):",
    "rsa_public_key_label": "کلید عمومی (PEM):",
    "rsa_private_key_label": "کلید خصوصی (PEM):",
    "encrypt_button_level1": "رمزگذاری",
    "decrypt_button_level1": "رمزگشایی",
    "encode_button_level2": "کدگذاری",
    "decode_button_level2": "کدبرداری",
    "hash_button_level3": "درهم‌سازی",
    "encrypt_button_level4": "رمزگذاری",
    "decrypt_button_level4": "رمزگشایی",
    "decrypt_button_level5": "رمزگشایی هوشمند",
    "mix_button_level6": "ترکیب الگوریتم‌ها",
    "encrypt_button_file": "رمزنگاری فایل",
    "decrypt_button_file": "رمزگشایی فایل",
    "select_file_button": "انتخاب فایل",
    "result_label": "نتیجه:",
    "theme_settings_label": "تنظیمات پوسته",
    "language_settings_label": "تنظیمات زبان",
    "select_language_label": "انتخاب زبان:",
    "color_settings_label": "تنظیمات رنگ",
    "button_color_label": "رنگ دکمه:",
    "use_system_colors_label": "استفاده از رنگ‌های سیستم",
    "key_generator_settings_label": "تنظیمات تولید کلید",
    "key_size_label": "اندازه کلید (بیت):",
    "generate_key_button": "تولید کلید",
    "key_result_label": "کلید تولید شده:",
    "rsa_key_generator_label": "تولید کننده جفت کلید RSA",
    "rsa_key_size_label": "اندازه کلید (بیت):",
    "generate_rsa_key_button": "تولید جفت کلید RSA",
    "copy_rsa_public_key_button": "کپی کلید عمومی",
    "copy_rsa_private_key_button": "کپی کلید خصوصی",
    "about_crypto_coder": "درباره کریپتو کودر",
    "about_text": """کریپتو کودر یک برنامه پیشرفته برای نمایش الگوریتم‌های رمزنگاری برای اهداف آموزشی است.

این برنامه شامل رمزگذاری‌های پیشرفته، روش‌های کدگذاری/کدبرداری، درهم‌سازی امن، الگوریتم‌های رمزنگاری، رمزگشایی هوشمند و ترکیب الگوریتم است.

**سلب مسئولیت:** این ابزار فقط برای استفاده آموزشی است. برای امنیت در سطح تولید، از کتابخانه‌های رمزنگاری بررسی‌شده و بهترین شیوه‌ها استفاده کنید.""",
    "clipboard_output_copied": "خروجی در حافظه کلیپ‌بورد کپی شد!",
    "clipboard_input_copied": "ورودی در حافظه کلیپ‌بورد کپی شد!",
    "clipboard_empty": "ورودی خالی است",
    "algorithm_error_title": "خطای الگوریتم",
    "vigenere_key_empty_error": "کلید ویژنر نمی‌تواند خالی باشد",
    "affine_key_error": "کلید 'a' آفین باید نسبت به 1114111 اول باشد و معتبر باشد",
    "rail_fence_rails_error": "تعداد ریل‌ها باید حداقل 1 باشد",
    "substitution_key_empty_error": "کلید جایگزینی نمی‌تواند خالی باشد",
    "playfair_key_empty_error": "کلید پلی‌فیر نمی‌تواند خالی باشد",
    "playfair_key_invalid_error": "کلید پلی‌فیر باید شامل حروف الفبا باشد",
    "polybius_input_error": "ورودی پلی‌بیوس نامعتبر: باید تعداد ارقام زوج باشد",
    "invalid_base64_input": "ورودی Base64 نامعتبر است",
    "invalid_url_input": "ورودی کدگذاری شده URL نامعتبر است",
    "invalid_hex_input": "ورودی شانزده‌شانزدهی نامعتبر است",
    "invalid_ascii_input": "ورودی ASCII نامعتبر است",
    "invalid_binary_input": "ورودی باینری نامعتبر است",
    "invalid_morse_input": "ورودی کد مورس نامعتبر است",
    "invalid_quoted_printable_input": "ورودی Quoted-Printable نامعتبر است",
    "invalid_unicode_escape_input": "ورودی Unicode Escape نامعتبر است",
    "invalid_base32_input": "ورودی Base32 نامعتبر است",
    "invalid_uuencode_input": "ورودی UUEncode نامعتبر است",
    "invalid_md5_input": "ورودی MD5 نامعتبر است",
    "invalid_sha1_input": "ورودی SHA1 نامعتبر است",
    "invalid_sha256_input": "ورودی SHA256 نامعتبر است",
    "invalid_sha512_input": "ورودی SHA512 نامعتبر است",
    "invalid_sha3_256_input": "ورودی SHA3_256 نامعتبر است",
    "invalid_sha3_512_input": "ورودی SHA3_512 نامعتبر است",
    "invalid_blake2b_input": "ورودی BLAKE2b نامعتبر است",
    "invalid_blake2s_input": "ورودی BLAKE2s نامعتبر است",
    "invalid_sha224_input": "ورودی SHA224 نامعتبر است",
    "invalid_sha384_input": "ورودی SHA384 نامعتبر است",
    "invalid_ripemd160_input": "ورودی RIPEMD160 نامعتبر است",
    "invalid_whirlpool_input": "ورودی Whirlpool نامعتبر است",
    "invalid_chacha20_input": "ورودی ChaCha20 نامعتبر است",
    "invalid_tripledes_input": "ورودی Triple DES نامعتبر است",
    "invalid_twofish_input": "ورودی Twofish نامعتبر است",
    "invalid_camellia_input": "ورودی Camellia نامعتبر است",
    "key_generation_error_title": "خطای تولید کلید",
    "key_copied_clipboard": "کلید در حافظه کلیپ‌بورد کپی شد!",
    "copy_key_button": "کپی کلید",
    "select_color_button": "انتخاب رنگ",
    "file_selected": "فایل انتخاب شده:",
    "no_file_selected": "هیچ فایلی انتخاب نشده",
    "file_encryption_success": "فایل با موفقیت رمزنگاری شد!",
    "file_decryption_success": "فایل با موفقیت رمزگشایی شد!",
    "file_encryption_error": "خطا در رمزنگاری فایل",
    "file_decryption_error": "خطا در رمزگشایی فایل",
    "select_file_first": "لطفاً ابتدا یک فایل انتخاب کنید.",
    "select_folder_button": "انتخاب پوشه",
    "hash_detected_title": "هش شناسایی شد",
    "hash_detected_message": "ورودی به نظر می‌رسد یک هش {0} باشد که یک تابع یک‌طرفه است و قابل رمزگشایی نیست. آیا مایلید با استفاده از منابع سخت‌افزاری برای شکستن آن تلاش کنید (این کار ممکن است زمان و منابع زیادی نیاز داشته باشد)؟",
    "hash_cracked_message": "هش {0} شکسته شد: {1}",
    "hash_cracking_failed": "شکستن هش {0} ناموفق بود. هیچ تطابقی در دیکشنری یافت نشد.",
    "hash_no_crack_message": "نمی‌توان هش {0} را بدون شکستن رمزگشایی کرد. لطفاً ورودی غیرهش ارائه دهید.",
    "encryption_detected_title": "رمزگذاری شناسایی شد",
    "encryption_detected_message": "ورودی ممکن است با {0} رمزگذاری شده باشد. آیا مایلید با استفاده از منابع سخت‌افزاری برای بازیابی کلید تلاش کنید (این کار ممکن است زمان زیادی ببرد)؟",
    "key_recovery_rsa_message": "بازیابی کلید RSA نیاز به کلید خصوصی یا تحلیل رمزنگاری دارد که در این نسخه امکان‌پذیر نیست.",
    "key_recovery_symmetric_message": "تلاش برای بازیابی کلید {0} به‌صورت شبیه‌سازی شده. این کار نیاز به منابع محاسباتی قابل توجهی دارد و پیاده‌سازی نشده است.",
    "cipher_detected_title": "رمز شناسایی شد",
    "cipher_detected_message": "ورودی به نظر می‌رسد با {0} رمزگذاری شده باشد. آیا مایلید با استفاده از منابع سخت‌افزاری برای بازیابی کلید تلاش کنید (این کار ممکن است زمان زیادی ببرد)؟",
    "cipher_no_crack_message": "نمی‌توان {0} را بدون بازیابی کلید رمزگشایی کرد. لطفاً ورودی دیگری ارائه دهید.",
    "key_recovery_cipher_message": "بازیابی کلید {0} ناموفق بود.",
    "key_recovery_failed": "بازیابی کلید برای {0} ناموفق بود.",
    "decode_failed": "خطا در رمزگشایی: خروجی قابل خواندن یافت نشد",
    "caesar_key_placeholder": "جابجایی سزار را وارد کنید (0-100)",
    "vigenere_key_placeholder": "کلید ویژنر را وارد کنید",
    "affine_key_placeholder": "کلیدهای آفین را وارد کنید (a,b)",
    "rail_fence_key_placeholder": "تعداد ریل‌ها را وارد کنید (1-10)",
    "substitution_key_placeholder": "کلید جایگزینی را وارد کنید",
    "playfair_key_placeholder": "کلید پلی‌فیر را وارد کنید",
    "caesar_shift_error": "جابجایی سزار باید عددی بین 0 و 100 باشد",
    "select_method_label": "انتخاب روش‌های رمزگشایی",
    "all_methods": "همه روش‌ها",
    "classical_ciphers": "رمزهای کلاسیک",
    "modern_ciphers": "رمزهای مدرن",
    "hash_methods": "کرک کردن هش",
    "no_methods_selected": "هیچ روشی برای رمزگشایی انتخاب نشده است.",
    "invalid_input_format": "فرمت ورودی برای {0} نامعتبر است.",
    "processing_timeout": "زمان پردازش برای {0} به پایان رسید. ورودی کوچک‌تر یا روش‌های کمتری امتحان کنید.",
    "base64_decode_error": "رمزگشایی Base64 ناموفق بود: فرمت نامعتبر.",
    "cancel_button": "لغو",
    "decryption_cancelled": "فرآیند رمزگشایی لغو شد.",
    "testing_algorithms": "در حال تست الگوریتم‌های رمزگذاری و کدگشایی...",
    "top_readable_results": "۵ نتیجه خواناترین:",
    "result_number": "نتیجه {0}:",
    "readability_score": "امتیاز خوانایی: {0}",
    "algorithm_used": "الگوریتم استفاده‌شده: {0}",
    "no_readable_results": "هیچ نتیجه خوانایی یافت نشد. ورودی دیگری امتحان کنید."
}

arabic_strings = {
    "level1_tab": "التشفيرات",
    "level2_tab": "المشفرات/فك التشفير",
    "level3_tab": "المهشرات",
    "level4_tab": "التشفير المتقدم",
    "level5_tab": "فك التشفير الذكي",
    "level6_tab": "خلاط الخوارزميات",
    "file_encryption_tab": "تشفير الملفات",
    "settings_tab": "الإعدادات",
    "enter_text_cipher": "أدخل النص للتشفير:",
    "enter_text_encode_decode": "أدخل النص للتشفير/فك التشفير:",
    "enter_text_hash": "أدخل النص للتهشير:",
    "enter_text_encryption": "أدخل النص للتشفير/فك التشفير:",
    "enter_text_smart_decrypt": "أدخل النص لفك التشفير:",
    "enter_text_mixer": "أدخل النص للخلط:",
    "clear_button": "مسح",
    "copy_input_button": "نسخ المدخلات",
    "paste_button": "لصق",
    "copy_output_button": "نسخ المخرجات",
    "select_algorithm_level1": "اختر التشفير:",
    "select_algorithm_level2": "اختر الخوارزمية:",
    "select_algorithm_level3": "اختر الخوارزمية:",
    "select_algorithm_level4": "اختر الخوارزمية:",
    "select_algorithm_level6": "اختر الخوارزميات للخلط:",
    "select_algorithm_file": "اختر الخوارزمية:",
    "caesar_shift_label": "إزاحة قيصر (0-100):",
    "vigenere_key_label": "مفتاح فيجنير:",
    "affine_a_label": "مفتاح أفين 'a':",
    "affine_b_label": "مفتاح أفين 'b':",
    "rail_fence_rails_label": "عدد السكك (1-10):",
    "substitution_key_label": "مفتاح الاستبدال:",
    "playfair_key_label": "مفتاح بلايفير:",
    "symmetric_key_label": "مفتاح متماثل (هيكس):",
    "rsa_public_key_label": "المفتاح العام (PEM):",
    "rsa_private_key_label": "المفتاح الخاص (PEM):",
    "encrypt_button_level1": "تشفير",
    "decrypt_button_level1": "فك التشفير",
    "encode_button_level2": "تشفير",
    "decode_button_level2": "فك التشفير",
    "hash_button_level3": "تهشير",
    "encrypt_button_level4": "تشفير",
    "decrypt_button_level4": "فك التشفير",
    "decrypt_button_level5": "فك تشفير ذكي",
    "mix_button_level6": "خلط الخوارزميات",
    "encrypt_button_file": "تشفير الملف",
    "decrypt_button_file": "فك تشفير الملف",
    "select_file_button": "اختر ملف",
    "result_label": "النتيجة:",
    "theme_settings_label": "إعدادات السمة",
    "language_settings_label": "إعدادات اللغة",
    "select_language_label": "اختر اللغة:",
    "color_settings_label": "إعدادات الألوان",
    "button_color_label": "لون الزر:",
    "use_system_colors_label": "استخدام ألوان النظام",
    "key_generator_settings_label": "إعدادات مولد المفاتيح",
    "key_size_label": "حجم المفتاح (بت):",
    "generate_key_button": "إنشاء مفتاح",
    "key_result_label": "المفتاح المُنشأ:",
    "rsa_key_generator_label": "مولد أزواج مفاتيح RSA",
    "rsa_key_size_label": "حجم المفتاح (بت):",
    "generate_rsa_key_button": "إنشاء زوج مفاتيح RSA",
    "copy_rsa_public_key_button": "نسخ المفتاح العام",
    "copy_rsa_private_key_button": "نسخ المفتاح الخاص",
    "about_crypto_coder": "عن Crypto Coder",
    "about_text": """Crypto Coder هو تطبيق متطور يعرض خوارزميات التشفير لأغراض تعليمية.

يتضمن تشفيرات متقدمة، وطرق تشفير/فك تشفير، وتهشير آمن، وخوارزميات تشفير، وفك تشفير ذكي، وخلط الخوارزميات.

**تنويه:** هذه الأداة مخصصة للاستخدام التعليمي فقط. للحصول على أمان على مستوى الإنتاج، اعتمد على مكتبات التشفير الموثقة وأفضل الممارسات.""",
    "clipboard_output_copied": "تم نسخ المخرجات إلى الحافظة!",
    "clipboard_input_copied": "تم نسخ المدخلات إلى الحافظة!",
    "clipboard_empty": "المدخلات فارغة",
    "algorithm_error_title": "خطأ في الخوارزمية",
    "vigenere_key_empty_error": "مفتاح فيجنير لا يمكن أن يكون فارغًا",
    "affine_key_error": "مفتاح أفين 'a' يجب أن يكون أوليًا نسبيًا مع 1114111 وصالحًا",
    "rail_fence_rails_error": "عدد السكك يجب أن يكون 1 على الأقل",
    "substitution_key_empty_error": "مفتاح الاستبدال لا يمكن أن يكون فارغًا",
    "playfair_key_empty_error": "مفتاح بلايفير لا يمكن أن يكون فارغًا",
    "playfair_key_invalid_error": "مفتاح بلايفير يجب أن يحتوي على حروف أبجدية",
    "polybius_input_error": "مدخل بوليبيوس غير صالح: يجب أن يحتوي على عدد زوجي من الأرقام",
    "invalid_base64_input": "مدخل Base64 غير صالح",
    "invalid_url_input": "مدخل URL مشفر غير صالح",
    "invalid_hex_input": "مدخل سداسي عشري غير صالح",
    "invalid_ascii_input": "مدخل ASCII غير صالح",
    "invalid_binary_input": "مدخل ثنائي غير صالح",
    "invalid_morse_input": "مدخل كود مورس غير صالح",
    "invalid_quoted_printable_input": "مدخل Quoted-Printable غير صالح",
    "invalid_unicode_escape_input": "مدخل Unicode Escape غير صالح",
    "invalid_base32_input": "مدخل Base32 غير صالح",
    "invalid_uuencode_input": "مدخل UUEncode غير صالح",
    "invalid_md5_input": "مدخل MD5 غير صالح",
    "invalid_sha1_input": "مدخل SHA1 غير صالح",
    "invalid_sha256_input": "مدخل SHA256 غير صالح",
    "invalid_sha512_input": "مدخل SHA512 غير صالح",
    "invalid_sha3_256_input": "مدخل SHA3_256 غير صالح",
    "invalid_sha3_512_input": "مدخل SHA3_512 غير صالح",
    "invalid_blake2b_input": "مدخل BLAKE2b غير صالح",
    "invalid_blake2s_input": "مدخل BLAKE2s غير صالح",
    "invalid_sha224_input": "مدخل SHA224 غير صالح",
    "invalid_sha384_input": "مدخل SHA384 غير صالح",
    "invalid_ripemd160_input": "مدخل RIPEMD160 غير صالح",
    "invalid_whirlpool_input": "مدخل Whirlpool غير صالح",
    "invalid_chacha20_input": "مدخل ChaCha20 غير صالح",
    "invalid_tripledes_input": "مدخل Triple DES غير صالح",
    "invalid_twofish_input": "مدخل Twofish غير صالح",
    "invalid_camellia_input": "مدخل Camellia غير صالح",
    "key_generation_error_title": "خطأ في إنشاء المفتاح",
    "key_copied_clipboard": "تم نسخ المفتاح إلى الحافظة!",
    "copy_key_button": "نسخ المفتاح",
    "select_color_button": "اختر اللون",
    "file_selected": "الملف المحدد:",
    "no_file_selected": "لم يتم تحديد ملف",
    "file_encryption_success": "تم تشفير الملف بنجاح!",
    "file_decryption_success": "تم فك تشفير الملف بنجاح!",
    "file_encryption_error": "خطأ في تشفير الملف",
    "file_decryption_error": "خطأ في فك تشفير الملف",
    "select_file_first": "يرجى تحديد ملف أولاً.",
    "select_folder_button": "اختر مجلد",
    "hash_detected_title": "تم اكتشاف الهاش",
    "hash_detected_message": "يبدو أن المدخل عبارة عن هاش {0}، وهو دالة أحادية الاتجاه ولا يمكن فك تشفيرها. هل ترغب في محاولة كسره باستخدام الموارد الأجهزة (قد يستغرق ذلك وقتًا وموارد كبيرة)؟",
    "hash_cracked_message": "تم كسر هاش {0}: {1}",
    "hash_cracking_failed": "فشل في كسر هاش {0}. لم يتم العثور على تطابق في القاموس.",
    "hash_no_crack_message": "لا يمكن فك تشفير هاش {0} بدون الكسر. يرجى تقديم مدخل غير هاش.",
    "encryption_detected_title": "تم اكتشاف التشفير",
    "encryption_detected_message": "قد يكون المدخل مشفرًا بـ {0}. هل ترغب في محاولة استرداد المفتاح باستخدام الموارد الأجهزة (قد يستغرق ذلك وقتًا طويلاً)؟",
    "key_recovery_rsa_message": "استرداد مفتاح RSA يتطلب المفتاح الخاص أو التحليل التشفيري، وهو غير ممكن في هذا الإصدار.",
    "key_recovery_symmetric_message": "محاولة كسر مفتاح {0} (محاكاة). يتطلب هذا موارد حسابية كبيرة ولم يتم تنفيذه.",
    "cipher_detected_title": "تم اكتشاف التشفير",
    "cipher_detected_message": "يبدو أن المدخل مشفر بـ {0}. هل ترغب في محاولة استرداد المفتاح باستخدام الموارد الأجهزة (قد يستغرق ذلك وقتًا طويلاً)؟",
    "cipher_no_crack_message": "لا يمكن فك تشفير {0} بدون استرداد المفتاح. يرجى تقديم مدخل مختلف.",
    "key_recovery_cipher_message": "فشل في استرداد مفتاح {0}.",
    "key_recovery_failed": "فشل في استرداد المفتاح لـ {0}.",
    "decode_failed": "فشل فك التشفير: لم يتم العثور على مخرجات قابلة للقراءة",
    "caesar_key_placeholder": "أدخل إزاحة قيصر (0-100)",
    "vigenere_key_placeholder": "أدخل مفتاح فيجنير",
    "affine_key_placeholder": "أدخل مفاتيح أفين (a,b)",
    "rail_fence_key_placeholder": "أدخل عدد السكك (1-10)",
    "substitution_key_placeholder": "أدخل مفتاح الاستبدال",
    "playfair_key_placeholder": "أدخل مفتاح بلايفير",
    "caesar_shift_error": "إزاحة قيصر يجب أن تكون رقمًا بين 0 و 100",
    "select_method_label": "اختر طرق فك التشفير",
    "all_methods": "جميع الطرق",
    "classical_ciphers": "التشفيرات الكلاسيكية",
    "modern_ciphers": "التشفيرات الحديثة",
    "hash_methods": "كسر الهاش",
    "no_methods_selected": "لم يتم اختيار أي طرق لفك التشفير.",
    "invalid_input_format": "تنسيق المدخل غير صالح لـ {0}.",
    "processing_timeout": "انتهى وقت المعالجة لـ {0}. جرب مدخلًا أصغر أو طرقًا أقل.",
    "base64_decode_error": "فشل فك تشفير Base64: تنسيق غير صالح.",
    "cancel_button": "إلغاء",
    "decryption_cancelled": "تم إلغاء عملية فك التشفير.",
    "testing_algorithms": "جاري اختبار الخوارزميات من التشفيرات والمشفرات/فك التشفير...",
    "top_readable_results": "أفضل 5 نتائج قابلة للقراءة:",
    "result_number": "النتيجة {0}:",
    "readability_score": "درجة القراءة: {0}",
    "algorithm_used": "الخوارزمية المستخدمة: {0}",
    "no_readable_results": "لم يتم العثور على نتائج قابلة للقراءة. جرب مدخلًا مختلفًا."
}